echo "work queue start"

python3 /Users/user/Desktop/python-rabbitMQ/new_task.py First message.
python3 /Users/user/Desktop/python-rabbitMQ/new_task.py Second message..
python3 /Users/user/Desktop/python-rabbitMQ/new_task.py Third message...
python3 /Users/user/Desktop/python-rabbitMQ/new_task.py Fourth message....
python3 /Users/user/Desktop/python-rabbitMQ/new_task.py Fifth message.....
